redis-cluster:
  enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  storageClass: directpv-min-io
  volumeMode: Filesystem

gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
  admin:
    username: "gitea-admin"
    password: "gitea-admin"

actions:
  enabled: true
  provisioning:
    enabled: true